import type { Client } from '../types/client';

export const mockClients: Client[] = [
  {
    id: 'cli-001',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@gmail.com',
    phone: '+91 98765 43210',
    company: 'Mehta Technologies Pvt. Ltd.',
    initials: 'AM',
    totalSessions: 3,
    totalHours: 3.1,
    lastSession: '2024-11-15',
    status: 'active',
    notes: 'Long-term client focused on tax optimization and equity investments. Prefers detailed written summaries after each session.',
    createdAt: '2024-01-15T09:00:00Z',
    avatarColor: '#6366f1',
  },
  {
    id: 'cli-002',
    name: 'Priya Sharma',
    email: 'priya.sharma@outlook.com',
    phone: '+91 87654 32109',
    company: 'Freelance Designer',
    initials: 'PS',
    totalSessions: 3,
    totalHours: 2.5,
    lastSession: '2024-11-12',
    status: 'active',
    notes: 'Young professional building wealth systematically. Very disciplined with SIPs. Goal: buy a home in 5 years.',
    createdAt: '2024-02-20T10:00:00Z',
    avatarColor: '#ec4899',
  },
  {
    id: 'cli-003',
    name: 'Vikram Nair',
    email: 'vikram.nair@nairgroup.in',
    phone: '+91 76543 21098',
    company: 'Nair Group Industries',
    initials: 'VN',
    totalSessions: 3,
    totalHours: 3.8,
    lastSession: '2024-11-10',
    status: 'active',
    notes: 'HNI client with complex estate planning needs. Multiple properties and business interests. Requires coordinated advisory with his CA.',
    createdAt: '2024-01-05T09:00:00Z',
    avatarColor: '#f59e0b',
  },
  {
    id: 'cli-004',
    name: 'Sneha Patel',
    email: 'sneha.patel@hotmail.com',
    phone: '+91 65432 10987',
    company: 'Government Employee (Education Dept.)',
    initials: 'SP',
    totalSessions: 3,
    totalHours: 2.7,
    lastSession: '2024-11-08',
    status: 'active',
    notes: 'Government employee interested in early retirement. Two school-age children. Conservative to moderate risk profile.',
    createdAt: '2024-03-10T10:00:00Z',
    avatarColor: '#10b981',
  },
  {
    id: 'cli-005',
    name: 'Rahul Gupta',
    email: 'rahul.gupta@infosys.com',
    phone: '+91 54321 09876',
    company: 'Infosys Ltd.',
    initials: 'RG',
    totalSessions: 3,
    totalHours: 2.1,
    lastSession: '2024-11-05',
    status: 'active',
    notes: 'Software engineer with significant RSU vesting. Focus on diversification away from concentrated tech stock position.',
    createdAt: '2024-02-01T10:00:00Z',
    avatarColor: '#3b82f6',
  },
  {
    id: 'cli-006',
    name: 'Kavitha Reddy',
    email: 'kavitha.reddy@reddylabs.com',
    phone: '+91 43210 98765',
    company: 'Reddy Pharma Labs',
    initials: 'KR',
    totalSessions: 3,
    totalHours: 2.7,
    lastSession: '2024-10-25',
    status: 'active',
    notes: 'Going through financial restructuring post-divorce. Needs comprehensive financial rebuild. Sensitive to privacy.',
    createdAt: '2024-04-15T10:00:00Z',
    avatarColor: '#8b5cf6',
  },
  {
    id: 'cli-007',
    name: 'Manish Agarwal',
    email: 'manish@agarwalventures.com',
    phone: '+91 32109 87654',
    company: 'Agarwal Ventures',
    initials: 'MA',
    totalSessions: 3,
    totalHours: 4.8,
    lastSession: '2024-10-22',
    status: 'active',
    notes: 'Serial entrepreneur with 3 active businesses. Complex shareholding structure. Aggressive growth mindset.',
    createdAt: '2024-01-20T10:00:00Z',
    avatarColor: '#f97316',
  },
  {
    id: 'cli-008',
    name: 'Divya Krishnan',
    email: 'divya.krishnan@gmail.com',
    phone: '+91 21098 76543',
    company: 'Krishnan & Associates (Law Firm)',
    initials: 'DK',
    totalSessions: 3,
    totalHours: 2.7,
    lastSession: '2024-10-18',
    status: 'active',
    notes: 'Lawyer with high income but erratic cash flows. Needs budgeting discipline and strategic investment planning.',
    createdAt: '2024-03-25T10:00:00Z',
    avatarColor: '#14b8a6',
  },
  {
    id: 'cli-009',
    name: 'Sunita Joshi',
    email: 'sunita.joshi@yahoo.com',
    phone: '+91 10987 65432',
    company: 'Retired (Former Bank Manager)',
    initials: 'SJ',
    totalSessions: 3,
    totalHours: 3.3,
    lastSession: '2024-10-10',
    status: 'active',
    notes: 'Recently retired. Primary concern is capital preservation and regular income. Very risk-averse.',
    createdAt: '2024-04-01T10:00:00Z',
    avatarColor: '#f43f5e',
  },
  {
    id: 'cli-010',
    name: 'Rohan Desai',
    email: 'rohan.desai@desaigroup.com',
    phone: '+91 99887 76655',
    company: 'Desai Group (USA-based NRI)',
    initials: 'RD',
    totalSessions: 3,
    totalHours: 3.6,
    lastSession: '2024-10-05',
    status: 'inactive',
    notes: 'NRI based in San Jose. Indian portfolio management and FEMA compliance. Son starting university in USA next year.',
    createdAt: '2024-02-10T10:00:00Z',
    avatarColor: '#0ea5e9',
  },
];
